//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LotusimSensor
{
    [Serializable]
    public class CollisionMsg : Message
    {
        public const string k_RosMessageName = "lotusim_sensor_msgs/Collision";
        public override string RosMessageName => k_RosMessageName;

        public double[] entity;

        public CollisionMsg()
        {
            this.entity = new double[0];
        }

        public CollisionMsg(double[] entity)
        {
            this.entity = entity;
        }

        public static CollisionMsg Deserialize(MessageDeserializer deserializer) => new CollisionMsg(deserializer);

        private CollisionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entity, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.entity);
            serializer.Write(this.entity);
        }

        public override string ToString()
        {
            return "CollisionMsg: " +
            "\nentity: " + System.String.Join(", ", entity.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
