//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LotusimSensor
{
    [Serializable]
    public class CollisionsMsg : Message
    {
        public const string k_RosMessageName = "lotusim_sensor_msgs/Collisions";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public CollisionMsg[] collisions;

        public CollisionsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.collisions = new CollisionMsg[0];
        }

        public CollisionsMsg(Std.HeaderMsg header, CollisionMsg[] collisions)
        {
            this.header = header;
            this.collisions = collisions;
        }

        public static CollisionsMsg Deserialize(MessageDeserializer deserializer) => new CollisionsMsg(deserializer);

        private CollisionsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.collisions, CollisionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.collisions);
            serializer.Write(this.collisions);
        }

        public override string ToString()
        {
            return "CollisionsMsg: " +
            "\nheader: " + header.ToString() +
            "\ncollisions: " + System.String.Join(", ", collisions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
