//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LotusimSensor
{
    [Serializable]
    public class PressureDepthMsg : Message
    {
        public const string k_RosMessageName = "lotusim_sensor_msgs/PressureDepth";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double pressure;
        public double depth;
        public double stddev;

        public PressureDepthMsg()
        {
            this.header = new Std.HeaderMsg();
            this.pressure = 0.0;
            this.depth = 0.0;
            this.stddev = 0.0;
        }

        public PressureDepthMsg(Std.HeaderMsg header, double pressure, double depth, double stddev)
        {
            this.header = header;
            this.pressure = pressure;
            this.depth = depth;
            this.stddev = stddev;
        }

        public static PressureDepthMsg Deserialize(MessageDeserializer deserializer) => new PressureDepthMsg(deserializer);

        private PressureDepthMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.pressure);
            deserializer.Read(out this.depth);
            deserializer.Read(out this.stddev);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pressure);
            serializer.Write(this.depth);
            serializer.Write(this.stddev);
        }

        public override string ToString()
        {
            return "PressureDepthMsg: " +
            "\nheader: " + header.ToString() +
            "\npressure: " + pressure.ToString() +
            "\ndepth: " + depth.ToString() +
            "\nstddev: " + stddev.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
