//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LotusimSensor
{
    [Serializable]
    public class RadarDetectionMsg : Message
    {
        public const string k_RosMessageName = "lotusim_sensor_msgs/RadarDetection";
        public override string RosMessageName => k_RosMessageName;

        public float range;
        //  metres
        public float azimuth;
        //  radians  (0 = bow, positive = port)
        public float intensity;
        //  0..1

        public RadarDetectionMsg()
        {
            this.range = 0.0f;
            this.azimuth = 0.0f;
            this.intensity = 0.0f;
        }

        public RadarDetectionMsg(float range, float azimuth, float intensity)
        {
            this.range = range;
            this.azimuth = azimuth;
            this.intensity = intensity;
        }

        public static RadarDetectionMsg Deserialize(MessageDeserializer deserializer) => new RadarDetectionMsg(deserializer);

        private RadarDetectionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.range);
            deserializer.Read(out this.azimuth);
            deserializer.Read(out this.intensity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.range);
            serializer.Write(this.azimuth);
            serializer.Write(this.intensity);
        }

        public override string ToString()
        {
            return "RadarDetectionMsg: " +
            "\nrange: " + range.ToString() +
            "\nazimuth: " + azimuth.ToString() +
            "\nintensity: " + intensity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
