//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LotusimSensor
{
    [Serializable]
    public class RadarScanMsg : Message
    {
        public const string k_RosMessageName = "lotusim_sensor_msgs/RadarScan";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public RadarDetectionMsg[] detections;

        public RadarScanMsg()
        {
            this.header = new Std.HeaderMsg();
            this.detections = new RadarDetectionMsg[0];
        }

        public RadarScanMsg(Std.HeaderMsg header, RadarDetectionMsg[] detections)
        {
            this.header = header;
            this.detections = detections;
        }

        public static RadarScanMsg Deserialize(MessageDeserializer deserializer) => new RadarScanMsg(deserializer);

        private RadarScanMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.detections, RadarDetectionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.detections);
            serializer.Write(this.detections);
        }

        public override string ToString()
        {
            return "RadarScanMsg: " +
            "\nheader: " + header.ToString() +
            "\ndetections: " + System.String.Join(", ", detections.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
