//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ExampleRos2Interface
{
    [Serializable]
    public class UserEventMsg : Message
    {
        public const string k_RosMessageName = "example_ros2_interface/UserEvent";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public const sbyte EXPLOSION = 0;
        public byte event_type;
        //  Event will either happen at the vessel position or given position
        public string vessel_name;
        public Geometry.PoseMsg position;

        public UserEventMsg()
        {
            this.header = new Std.HeaderMsg();
            this.event_type = 0;
            this.vessel_name = "";
            this.position = new Geometry.PoseMsg();
        }

        public UserEventMsg(Std.HeaderMsg header, byte event_type, string vessel_name, Geometry.PoseMsg position)
        {
            this.header = header;
            this.event_type = event_type;
            this.vessel_name = vessel_name;
            this.position = position;
        }

        public static UserEventMsg Deserialize(MessageDeserializer deserializer) => new UserEventMsg(deserializer);

        private UserEventMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.event_type);
            deserializer.Read(out this.vessel_name);
            this.position = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.event_type);
            serializer.Write(this.vessel_name);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "UserEventMsg: " +
            "\nheader: " + header.ToString() +
            "\nevent_type: " + event_type.ToString() +
            "\nvessel_name: " + vessel_name.ToString() +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
