//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class MASCmdGoal : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/MASCmd";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public MASCmdMsg cmd;

        public MASCmdGoal()
        {
            this.header = new Std.HeaderMsg();
            this.cmd = new MASCmdMsg();
        }

        public MASCmdGoal(Std.HeaderMsg header, MASCmdMsg cmd)
        {
            this.header = header;
            this.cmd = cmd;
        }

        public static MASCmdGoal Deserialize(MessageDeserializer deserializer) => new MASCmdGoal(deserializer);

        private MASCmdGoal(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.cmd = MASCmdMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "MASCmdGoal: " +
            "\nheader: " + header.ToString() +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
