//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class MASCmdArrayResult : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/MASCmdArray";
        public override string RosMessageName => k_RosMessageName;

        public bool[] result;
        public string[] name;
        public ushort[] entity;

        public MASCmdArrayResult()
        {
            this.result = new bool[0];
            this.name = new string[0];
            this.entity = new ushort[0];
        }

        public MASCmdArrayResult(bool[] result, string[] name, ushort[] entity)
        {
            this.result = result;
            this.name = name;
            this.entity = entity;
        }

        public static MASCmdArrayResult Deserialize(MessageDeserializer deserializer) => new MASCmdArrayResult(deserializer);

        private MASCmdArrayResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result, sizeof(bool), deserializer.ReadLength());
            deserializer.Read(out this.name, deserializer.ReadLength());
            deserializer.Read(out this.entity, sizeof(ushort), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.result);
            serializer.Write(this.result);
            serializer.WriteLength(this.name);
            serializer.Write(this.name);
            serializer.WriteLength(this.entity);
            serializer.Write(this.entity);
        }

        public override string ToString()
        {
            return "MASCmdArrayResult: " +
            "\nresult: " + System.String.Join(", ", result.ToList()) +
            "\nname: " + System.String.Join(", ", name.ToList()) +
            "\nentity: " + System.String.Join(", ", entity.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
