//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class MASCmdResult : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/MASCmd";
        public override string RosMessageName => k_RosMessageName;

        public bool result;
        public string name;
        public ushort entity;

        public MASCmdResult()
        {
            this.result = false;
            this.name = "";
            this.entity = 0;
        }

        public MASCmdResult(bool result, string name, ushort entity)
        {
            this.result = result;
            this.name = name;
            this.entity = entity;
        }

        public static MASCmdResult Deserialize(MessageDeserializer deserializer) => new MASCmdResult(deserializer);

        private MASCmdResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
            deserializer.Read(out this.name);
            deserializer.Read(out this.entity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.name);
            serializer.Write(this.entity);
        }

        public override string ToString()
        {
            return "MASCmdResult: " +
            "\nresult: " + result.ToString() +
            "\nname: " + name.ToString() +
            "\nentity: " + entity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
