//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class MASCmdFeedback : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/MASCmd";
        public override string RosMessageName => k_RosMessageName;

        public bool fb;

        public MASCmdFeedback()
        {
            this.fb = false;
        }

        public MASCmdFeedback(bool fb)
        {
            this.fb = fb;
        }

        public static MASCmdFeedback Deserialize(MessageDeserializer deserializer) => new MASCmdFeedback(deserializer);

        private MASCmdFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.fb);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.fb);
        }

        public override string ToString()
        {
            return "MASCmdFeedback: " +
            "\nfb: " + fb.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
