//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class MASCmdArrayGoal : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/MASCmdArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public MASCmdMsg[] cmd;

        public MASCmdArrayGoal()
        {
            this.header = new Std.HeaderMsg();
            this.cmd = new MASCmdMsg[0];
        }

        public MASCmdArrayGoal(Std.HeaderMsg header, MASCmdMsg[] cmd)
        {
            this.header = header;
            this.cmd = cmd;
        }

        public static MASCmdArrayGoal Deserialize(MessageDeserializer deserializer) => new MASCmdArrayGoal(deserializer);

        private MASCmdArrayGoal(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.cmd, MASCmdMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.cmd);
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "MASCmdArrayGoal: " +
            "\nheader: " + header.ToString() +
            "\ncmd: " + System.String.Join(", ", cmd.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
