//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GetGeoPathRequest : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GetGeoPath";
        public override string RosMessageName => k_RosMessageName;

        //  Searches for given start and goal the nearest route segments
        //  and determine the path through the RouteNetwork
        public GeoPointMsg start;
        //  starting point
        public GeoPointMsg goal;
        //  goal point

        public GetGeoPathRequest()
        {
            this.start = new GeoPointMsg();
            this.goal = new GeoPointMsg();
        }

        public GetGeoPathRequest(GeoPointMsg start, GeoPointMsg goal)
        {
            this.start = start;
            this.goal = goal;
        }

        public static GetGeoPathRequest Deserialize(MessageDeserializer deserializer) => new GetGeoPathRequest(deserializer);

        private GetGeoPathRequest(MessageDeserializer deserializer)
        {
            this.start = GeoPointMsg.Deserialize(deserializer);
            this.goal = GeoPointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start);
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "GetGeoPathRequest: " +
            "\nstart: " + start.ToString() +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
