//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GetRoutePlanResponse : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GetRoutePlan";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  true if the call succeeded
        public string status;
        //  more details
        public RoutePathMsg plan;
        //  path to follow

        public GetRoutePlanResponse()
        {
            this.success = false;
            this.status = "";
            this.plan = new RoutePathMsg();
        }

        public GetRoutePlanResponse(bool success, string status, RoutePathMsg plan)
        {
            this.success = success;
            this.status = status;
            this.plan = plan;
        }

        public static GetRoutePlanResponse Deserialize(MessageDeserializer deserializer) => new GetRoutePlanResponse(deserializer);

        private GetRoutePlanResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.status);
            this.plan = RoutePathMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.status);
            serializer.Write(this.plan);
        }

        public override string ToString()
        {
            return "GetRoutePlanResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nstatus: " + status.ToString() +
            "\nplan: " + plan.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
