//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class UpdateGeographicMapRequest : Message
    {
        public const string k_RosMessageName = "geographic_msgs/UpdateGeographicMap";
        public override string RosMessageName => k_RosMessageName;

        //  This service updates a geographic map.
        //  Changes to geographic map.
        public GeographicMapChangesMsg updates;

        public UpdateGeographicMapRequest()
        {
            this.updates = new GeographicMapChangesMsg();
        }

        public UpdateGeographicMapRequest(GeographicMapChangesMsg updates)
        {
            this.updates = updates;
        }

        public static UpdateGeographicMapRequest Deserialize(MessageDeserializer deserializer) => new UpdateGeographicMapRequest(deserializer);

        private UpdateGeographicMapRequest(MessageDeserializer deserializer)
        {
            this.updates = GeographicMapChangesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.updates);
        }

        public override string ToString()
        {
            return "UpdateGeographicMapRequest: " +
            "\nupdates: " + updates.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
