//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class UpdateGeographicMapResponse : Message
    {
        public const string k_RosMessageName = "geographic_msgs/UpdateGeographicMap";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  true if the call succeeded
        public string status;
        //  more details

        public UpdateGeographicMapResponse()
        {
            this.success = false;
            this.status = "";
        }

        public UpdateGeographicMapResponse(bool success, string status)
        {
            this.success = success;
            this.status = status;
        }

        public static UpdateGeographicMapResponse Deserialize(MessageDeserializer deserializer) => new UpdateGeographicMapResponse(deserializer);

        private UpdateGeographicMapResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "UpdateGeographicMapResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
