//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class EventMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/Event";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public const sbyte CREATE_EVENT = 0; //  only fill in sdf_string
        public const sbyte DELETE_EVENT = 1; //  only fill in entity or vessel_name
        public const sbyte OTHER_EVENT = 1; //  only fill in entity or vessel_name
        public byte event_type;
        //  Name of vessel in gazebo
        public string vessel_name;
        public Geometry.PoseMsg vessel_position;
        //  Description of event.
        public string @event;

        public EventMsg()
        {
            this.header = new Std.HeaderMsg();
            this.event_type = 0;
            this.vessel_name = "";
            this.vessel_position = new Geometry.PoseMsg();
            this.@event = "";
        }

        public EventMsg(Std.HeaderMsg header, byte event_type, string vessel_name, Geometry.PoseMsg vessel_position, string @event)
        {
            this.header = header;
            this.event_type = event_type;
            this.vessel_name = vessel_name;
            this.vessel_position = vessel_position;
            this.@event = @event;
        }

        public static EventMsg Deserialize(MessageDeserializer deserializer) => new EventMsg(deserializer);

        private EventMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.event_type);
            deserializer.Read(out this.vessel_name);
            this.vessel_position = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.@event);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.event_type);
            serializer.Write(this.vessel_name);
            serializer.Write(this.vessel_position);
            serializer.Write(this.@event);
        }

        public override string ToString()
        {
            return "EventMsg: " +
            "\nheader: " + header.ToString() +
            "\nevent_type: " + event_type.ToString() +
            "\nvessel_name: " + vessel_name.ToString() +
            "\nvessel_position: " + vessel_position.ToString() +
            "\n@event: " + @event.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
