//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class GPSMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/GPS";
        public override string RosMessageName => k_RosMessageName;

        //  Adding velocity to the current msg
        public Std.HeaderMsg header;
        public Sensor.NavSatStatusMsg status;
        public double latitude;
        public double longitude;
        public double altitude;
        public double[] position_covariance;
        public const byte COVARIANCE_TYPE_UNKNOWN = 0;
        public const byte COVARIANCE_TYPE_APPROXIMATED = 1;
        public const byte COVARIANCE_TYPE_DIAGONAL_KNOWN = 2;
        public const byte COVARIANCE_TYPE_KNOWN = 3;
        public byte position_covariance_type;
        //  Velocity is ENU
        public Geometry.Vector3Msg linear_velocity;

        public GPSMsg()
        {
            this.header = new Std.HeaderMsg();
            this.status = new Sensor.NavSatStatusMsg();
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.altitude = 0.0;
            this.position_covariance = new double[9];
            this.position_covariance_type = 0;
            this.linear_velocity = new Geometry.Vector3Msg();
        }

        public GPSMsg(Std.HeaderMsg header, Sensor.NavSatStatusMsg status, double latitude, double longitude, double altitude, double[] position_covariance, byte position_covariance_type, Geometry.Vector3Msg linear_velocity)
        {
            this.header = header;
            this.status = status;
            this.latitude = latitude;
            this.longitude = longitude;
            this.altitude = altitude;
            this.position_covariance = position_covariance;
            this.position_covariance_type = position_covariance_type;
            this.linear_velocity = linear_velocity;
        }

        public static GPSMsg Deserialize(MessageDeserializer deserializer) => new GPSMsg(deserializer);

        private GPSMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.status = Sensor.NavSatStatusMsg.Deserialize(deserializer);
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
            deserializer.Read(out this.altitude);
            deserializer.Read(out this.position_covariance, sizeof(double), 9);
            deserializer.Read(out this.position_covariance_type);
            this.linear_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.status);
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
            serializer.Write(this.altitude);
            serializer.Write(this.position_covariance);
            serializer.Write(this.position_covariance_type);
            serializer.Write(this.linear_velocity);
        }

        public override string ToString()
        {
            return "GPSMsg: " +
            "\nheader: " + header.ToString() +
            "\nstatus: " + status.ToString() +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString() +
            "\naltitude: " + altitude.ToString() +
            "\nposition_covariance: " + System.String.Join(", ", position_covariance.ToList()) +
            "\nposition_covariance_type: " + position_covariance_type.ToString() +
            "\nlinear_velocity: " + linear_velocity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
