//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class MASCmdMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/MASCmd";
        public override string RosMessageName => k_RosMessageName;

        //  Built in commands
        public const sbyte CREATE_CMD = 0; //  only fill in sdf_string
        public const sbyte DELETE_CMD = 1; //  only fill in entity or vessel_name
        public const sbyte MOVE_CMD = 2; //  only fill in (entity or vessel_name) and vessel_position
        public byte cmd_type;
        //  sdf definition in string if creation type
        public string sdf_string;
        //  If model has been created with folder in `assets/models` directory, sdf will be retrieved. 
        //  Lotusim param will be retrieved from sdf_string
        public string model_name;
        //  Name of vessel in gazebo
        public string vessel_name;
        //  ID of vessel in gazebo. 
        //  During creation, the entity entered does not matter and will be overwritten
        public ushort entity;
        //  vessel position if create or modify cmd
        public Geometry.PoseMsg vessel_position;
        public Geographic.GeoPointMsg geo_point;
        public float heading;

        public MASCmdMsg()
        {
            this.cmd_type = 0;
            this.sdf_string = "";
            this.model_name = "";
            this.vessel_name = "";
            this.entity = 0;
            this.vessel_position = new Geometry.PoseMsg();
            this.geo_point = new Geographic.GeoPointMsg();
            this.heading = 0.0f;
        }

        public MASCmdMsg(byte cmd_type, string sdf_string, string model_name, string vessel_name, ushort entity, Geometry.PoseMsg vessel_position, Geographic.GeoPointMsg geo_point, float heading)
        {
            this.cmd_type = cmd_type;
            this.sdf_string = sdf_string;
            this.model_name = model_name;
            this.vessel_name = vessel_name;
            this.entity = entity;
            this.vessel_position = vessel_position;
            this.geo_point = geo_point;
            this.heading = heading;
        }

        public static MASCmdMsg Deserialize(MessageDeserializer deserializer) => new MASCmdMsg(deserializer);

        private MASCmdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd_type);
            deserializer.Read(out this.sdf_string);
            deserializer.Read(out this.model_name);
            deserializer.Read(out this.vessel_name);
            deserializer.Read(out this.entity);
            this.vessel_position = Geometry.PoseMsg.Deserialize(deserializer);
            this.geo_point = Geographic.GeoPointMsg.Deserialize(deserializer);
            deserializer.Read(out this.heading);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd_type);
            serializer.Write(this.sdf_string);
            serializer.Write(this.model_name);
            serializer.Write(this.vessel_name);
            serializer.Write(this.entity);
            serializer.Write(this.vessel_position);
            serializer.Write(this.geo_point);
            serializer.Write(this.heading);
        }

        public override string ToString()
        {
            return "MASCmdMsg: " +
            "\ncmd_type: " + cmd_type.ToString() +
            "\nsdf_string: " + sdf_string.ToString() +
            "\nmodel_name: " + model_name.ToString() +
            "\nvessel_name: " + vessel_name.ToString() +
            "\nentity: " + entity.ToString() +
            "\nvessel_position: " + vessel_position.ToString() +
            "\ngeo_point: " + geo_point.ToString() +
            "\nheading: " + heading.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
