//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class SimStatsMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/SimStats";
        public override string RosMessageName => k_RosMessageName;

        //  This message communicates ROS Time defined here:
        //  https://design.ros2.org/articles/clock_and_time.html
        public BuiltinInterfaces.TimeMsg sim_time;
        public BuiltinInterfaces.TimeMsg real_time;
        public ulong iterations;
        public double real_time_factor;
        public BuiltinInterfaces.DurationMsg step_size;

        public SimStatsMsg()
        {
            this.sim_time = new BuiltinInterfaces.TimeMsg();
            this.real_time = new BuiltinInterfaces.TimeMsg();
            this.iterations = 0;
            this.real_time_factor = 0.0;
            this.step_size = new BuiltinInterfaces.DurationMsg();
        }

        public SimStatsMsg(BuiltinInterfaces.TimeMsg sim_time, BuiltinInterfaces.TimeMsg real_time, ulong iterations, double real_time_factor, BuiltinInterfaces.DurationMsg step_size)
        {
            this.sim_time = sim_time;
            this.real_time = real_time;
            this.iterations = iterations;
            this.real_time_factor = real_time_factor;
            this.step_size = step_size;
        }

        public static SimStatsMsg Deserialize(MessageDeserializer deserializer) => new SimStatsMsg(deserializer);

        private SimStatsMsg(MessageDeserializer deserializer)
        {
            this.sim_time = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.real_time = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.iterations);
            deserializer.Read(out this.real_time_factor);
            this.step_size = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sim_time);
            serializer.Write(this.real_time);
            serializer.Write(this.iterations);
            serializer.Write(this.real_time_factor);
            serializer.Write(this.step_size);
        }

        public override string ToString()
        {
            return "SimStatsMsg: " +
            "\nsim_time: " + sim_time.ToString() +
            "\nreal_time: " + real_time.ToString() +
            "\niterations: " + iterations.ToString() +
            "\nreal_time_factor: " + real_time_factor.ToString() +
            "\nstep_size: " + step_size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
