//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class VesselCmdMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/VesselCmd";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string vessel_name;
        public ushort entity;
        //  cmd in json string format
        public string cmd_string;

        public VesselCmdMsg()
        {
            this.header = new Std.HeaderMsg();
            this.vessel_name = "";
            this.entity = 0;
            this.cmd_string = "";
        }

        public VesselCmdMsg(Std.HeaderMsg header, string vessel_name, ushort entity, string cmd_string)
        {
            this.header = header;
            this.vessel_name = vessel_name;
            this.entity = entity;
            this.cmd_string = cmd_string;
        }

        public static VesselCmdMsg Deserialize(MessageDeserializer deserializer) => new VesselCmdMsg(deserializer);

        private VesselCmdMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.vessel_name);
            deserializer.Read(out this.entity);
            deserializer.Read(out this.cmd_string);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.vessel_name);
            serializer.Write(this.entity);
            serializer.Write(this.cmd_string);
        }

        public override string ToString()
        {
            return "VesselCmdMsg: " +
            "\nheader: " + header.ToString() +
            "\nvessel_name: " + vessel_name.ToString() +
            "\nentity: " + entity.ToString() +
            "\ncmd_string: " + cmd_string.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
