//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class VesselPositionArrayMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/VesselPositionArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public VesselPositionMsg[] vessels;

        public VesselPositionArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.vessels = new VesselPositionMsg[0];
        }

        public VesselPositionArrayMsg(Std.HeaderMsg header, VesselPositionMsg[] vessels)
        {
            this.header = header;
            this.vessels = vessels;
        }

        public static VesselPositionArrayMsg Deserialize(MessageDeserializer deserializer) => new VesselPositionArrayMsg(deserializer);

        private VesselPositionArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.vessels, VesselPositionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.vessels);
            serializer.Write(this.vessels);
        }

        public override string ToString()
        {
            return "VesselPositionArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nvessels: " + System.String.Join(", ", vessels.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
