//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class WindMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/Wind";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.Vector3Msg linear_velocity;
        public bool enable_wind;

        public WindMsg()
        {
            this.linear_velocity = new Geometry.Vector3Msg();
            this.enable_wind = false;
        }

        public WindMsg(Geometry.Vector3Msg linear_velocity, bool enable_wind)
        {
            this.linear_velocity = linear_velocity;
            this.enable_wind = enable_wind;
        }

        public static WindMsg Deserialize(MessageDeserializer deserializer) => new WindMsg(deserializer);

        private WindMsg(MessageDeserializer deserializer)
        {
            this.linear_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.enable_wind);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.linear_velocity);
            serializer.Write(this.enable_wind);
        }

        public override string ToString()
        {
            return "WindMsg: " +
            "\nlinear_velocity: " + linear_velocity.ToString() +
            "\nenable_wind: " + enable_wind.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
