//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LotusimSensor
{
    [Serializable]
    public class ActivateSensorRequest : Message
    {
        public const string k_RosMessageName = "lotusim_sensor_msgs/ActivateSensor";
        public override string RosMessageName => k_RosMessageName;

        public bool activate;

        public ActivateSensorRequest()
        {
            this.activate = false;
        }

        public ActivateSensorRequest(bool activate)
        {
            this.activate = activate;
        }

        public static ActivateSensorRequest Deserialize(MessageDeserializer deserializer) => new ActivateSensorRequest(deserializer);

        private ActivateSensorRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.activate);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.activate);
        }

        public override string ToString()
        {
            return "ActivateSensorRequest: " +
            "\nactivate: " + activate.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
