//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LotusimSensor
{
    [Serializable]
    public class ActivateSensorResponse : Message
    {
        public const string k_RosMessageName = "lotusim_sensor_msgs/ActivateSensor";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public ActivateSensorResponse()
        {
            this.success = false;
        }

        public ActivateSensorResponse(bool success)
        {
            this.success = success;
        }

        public static ActivateSensorResponse Deserialize(MessageDeserializer deserializer) => new ActivateSensorResponse(deserializer);

        private ActivateSensorResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ActivateSensorResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
