//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class AISArrayMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/AISArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public AISMsg[] data;

        public AISArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.data = new AISMsg[0];
        }

        public AISArrayMsg(Std.HeaderMsg header, AISMsg[] data)
        {
            this.header = header;
            this.data = data;
        }

        public static AISArrayMsg Deserialize(MessageDeserializer deserializer) => new AISArrayMsg(deserializer);

        private AISArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, AISMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "AISArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
