//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class AISMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/AIS";
        public override string RosMessageName => k_RosMessageName;

        public uint user_id;
        public string name;
        public uint navigation_status;
        //  Not set yet
        public double rot;
        //  rate of turn # Not set yet
        public double sog;
        //  speed over ground
        public double positional_accuracy;
        //  Not set yet
        public double longitude;
        public double latitude;
        public double true_heading;
        //  Not set yet
        public double cog;

        public AISMsg()
        {
            this.user_id = 0;
            this.name = "";
            this.navigation_status = 0;
            this.rot = 0.0;
            this.sog = 0.0;
            this.positional_accuracy = 0.0;
            this.longitude = 0.0;
            this.latitude = 0.0;
            this.true_heading = 0.0;
            this.cog = 0.0;
        }

        public AISMsg(uint user_id, string name, uint navigation_status, double rot, double sog, double positional_accuracy, double longitude, double latitude, double true_heading, double cog)
        {
            this.user_id = user_id;
            this.name = name;
            this.navigation_status = navigation_status;
            this.rot = rot;
            this.sog = sog;
            this.positional_accuracy = positional_accuracy;
            this.longitude = longitude;
            this.latitude = latitude;
            this.true_heading = true_heading;
            this.cog = cog;
        }

        public static AISMsg Deserialize(MessageDeserializer deserializer) => new AISMsg(deserializer);

        private AISMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.user_id);
            deserializer.Read(out this.name);
            deserializer.Read(out this.navigation_status);
            deserializer.Read(out this.rot);
            deserializer.Read(out this.sog);
            deserializer.Read(out this.positional_accuracy);
            deserializer.Read(out this.longitude);
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.true_heading);
            deserializer.Read(out this.cog);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.user_id);
            serializer.Write(this.name);
            serializer.Write(this.navigation_status);
            serializer.Write(this.rot);
            serializer.Write(this.sog);
            serializer.Write(this.positional_accuracy);
            serializer.Write(this.longitude);
            serializer.Write(this.latitude);
            serializer.Write(this.true_heading);
            serializer.Write(this.cog);
        }

        public override string ToString()
        {
            return "AISMsg: " +
            "\nuser_id: " + user_id.ToString() +
            "\nname: " + name.ToString() +
            "\nnavigation_status: " + navigation_status.ToString() +
            "\nrot: " + rot.ToString() +
            "\nsog: " + sog.ToString() +
            "\npositional_accuracy: " + positional_accuracy.ToString() +
            "\nlongitude: " + longitude.ToString() +
            "\nlatitude: " + latitude.ToString() +
            "\ntrue_heading: " + true_heading.ToString() +
            "\ncog: " + cog.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
