//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class GuidanceSetpointMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/GuidanceSetpoint";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  True: Control must drive directly toward (target_x, target_y) in the
        //  horizontal plane. False: Control tracks desired_heading and desired_speed
        //  instead.
        public bool use_position_hold;
        public double target_x;
        //  m, valid only if use_position_hold
        public double target_y;
        //  m, valid only if use_position_hold
        public double desired_heading;
        //  rad, positive clockwise from above
        public double desired_depth;
        //  m, positive down
        public double desired_speed;
        //  m/s, surge -- valid only if not use_position_hold
        public double cross_track_error;
        //  m, signed; 0 if use_position_hold
        public double along_track_distance;
        //  m, from the start of the current leg; 0 if use_position_hold
        public bool arrived;

        public GuidanceSetpointMsg()
        {
            this.header = new Std.HeaderMsg();
            this.use_position_hold = false;
            this.target_x = 0.0;
            this.target_y = 0.0;
            this.desired_heading = 0.0;
            this.desired_depth = 0.0;
            this.desired_speed = 0.0;
            this.cross_track_error = 0.0;
            this.along_track_distance = 0.0;
            this.arrived = false;
        }

        public GuidanceSetpointMsg(Std.HeaderMsg header, bool use_position_hold, double target_x, double target_y, double desired_heading, double desired_depth, double desired_speed, double cross_track_error, double along_track_distance, bool arrived)
        {
            this.header = header;
            this.use_position_hold = use_position_hold;
            this.target_x = target_x;
            this.target_y = target_y;
            this.desired_heading = desired_heading;
            this.desired_depth = desired_depth;
            this.desired_speed = desired_speed;
            this.cross_track_error = cross_track_error;
            this.along_track_distance = along_track_distance;
            this.arrived = arrived;
        }

        public static GuidanceSetpointMsg Deserialize(MessageDeserializer deserializer) => new GuidanceSetpointMsg(deserializer);

        private GuidanceSetpointMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.use_position_hold);
            deserializer.Read(out this.target_x);
            deserializer.Read(out this.target_y);
            deserializer.Read(out this.desired_heading);
            deserializer.Read(out this.desired_depth);
            deserializer.Read(out this.desired_speed);
            deserializer.Read(out this.cross_track_error);
            deserializer.Read(out this.along_track_distance);
            deserializer.Read(out this.arrived);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.use_position_hold);
            serializer.Write(this.target_x);
            serializer.Write(this.target_y);
            serializer.Write(this.desired_heading);
            serializer.Write(this.desired_depth);
            serializer.Write(this.desired_speed);
            serializer.Write(this.cross_track_error);
            serializer.Write(this.along_track_distance);
            serializer.Write(this.arrived);
        }

        public override string ToString()
        {
            return "GuidanceSetpointMsg: " +
            "\nheader: " + header.ToString() +
            "\nuse_position_hold: " + use_position_hold.ToString() +
            "\ntarget_x: " + target_x.ToString() +
            "\ntarget_y: " + target_y.ToString() +
            "\ndesired_heading: " + desired_heading.ToString() +
            "\ndesired_depth: " + desired_depth.ToString() +
            "\ndesired_speed: " + desired_speed.ToString() +
            "\ncross_track_error: " + cross_track_error.ToString() +
            "\nalong_track_distance: " + along_track_distance.ToString() +
            "\narrived: " + arrived.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
