//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class OceanCurrentMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/OceanCurrent";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.Vector3Msg linear_velocity;
        public bool enable_current;

        public OceanCurrentMsg()
        {
            this.linear_velocity = new Geometry.Vector3Msg();
            this.enable_current = false;
        }

        public OceanCurrentMsg(Geometry.Vector3Msg linear_velocity, bool enable_current)
        {
            this.linear_velocity = linear_velocity;
            this.enable_current = enable_current;
        }

        public static OceanCurrentMsg Deserialize(MessageDeserializer deserializer) => new OceanCurrentMsg(deserializer);

        private OceanCurrentMsg(MessageDeserializer deserializer)
        {
            this.linear_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.enable_current);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.linear_velocity);
            serializer.Write(this.enable_current);
        }

        public override string ToString()
        {
            return "OceanCurrentMsg: " +
            "\nlinear_velocity: " + linear_velocity.ToString() +
            "\nenable_current: " + enable_current.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
