//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class RendererCmdMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/RendererCmd";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public const sbyte CREATE_CMD = 0; //  only fill in sdf_string
        public const sbyte DELETE_CMD = 1; //  only fill in vessel_name
        public const sbyte EXPLODE_CMD = 2; //  only fill in vessel_name
        public byte cmd_type;
        //  sdf definition in string if creation type
        public string renderer_obj_name;
        public string vessel_name;
        //  vessel position if create or modify cmd
        public Geometry.PoseMsg vessel_position;

        public RendererCmdMsg()
        {
            this.header = new Std.HeaderMsg();
            this.cmd_type = 0;
            this.renderer_obj_name = "";
            this.vessel_name = "";
            this.vessel_position = new Geometry.PoseMsg();
        }

        public RendererCmdMsg(Std.HeaderMsg header, byte cmd_type, string renderer_obj_name, string vessel_name, Geometry.PoseMsg vessel_position)
        {
            this.header = header;
            this.cmd_type = cmd_type;
            this.renderer_obj_name = renderer_obj_name;
            this.vessel_name = vessel_name;
            this.vessel_position = vessel_position;
        }

        public static RendererCmdMsg Deserialize(MessageDeserializer deserializer) => new RendererCmdMsg(deserializer);

        private RendererCmdMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.cmd_type);
            deserializer.Read(out this.renderer_obj_name);
            deserializer.Read(out this.vessel_name);
            this.vessel_position = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.cmd_type);
            serializer.Write(this.renderer_obj_name);
            serializer.Write(this.vessel_name);
            serializer.Write(this.vessel_position);
        }

        public override string ToString()
        {
            return "RendererCmdMsg: " +
            "\nheader: " + header.ToString() +
            "\ncmd_type: " + cmd_type.ToString() +
            "\nrenderer_obj_name: " + renderer_obj_name.ToString() +
            "\nvessel_name: " + vessel_name.ToString() +
            "\nvessel_position: " + vessel_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
