//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class VesselCmdArrayMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/VesselCmdArray";
        public override string RosMessageName => k_RosMessageName;

        public VesselCmdMsg[] cmds;

        public VesselCmdArrayMsg()
        {
            this.cmds = new VesselCmdMsg[0];
        }

        public VesselCmdArrayMsg(VesselCmdMsg[] cmds)
        {
            this.cmds = cmds;
        }

        public static VesselCmdArrayMsg Deserialize(MessageDeserializer deserializer) => new VesselCmdArrayMsg(deserializer);

        private VesselCmdArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmds, VesselCmdMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.cmds);
            serializer.Write(this.cmds);
        }

        public override string ToString()
        {
            return "VesselCmdArrayMsg: " +
            "\ncmds: " + System.String.Join(", ", cmds.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
