//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class VesselPositionMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/VesselPosition";
        public override string RosMessageName => k_RosMessageName;

        public string vessel_name;
        public Geometry.PoseMsg pose;
        //  Orientation uses front-left-up
        public Geographic.GeoPointMsg geo_point;

        public VesselPositionMsg()
        {
            this.vessel_name = "";
            this.pose = new Geometry.PoseMsg();
            this.geo_point = new Geographic.GeoPointMsg();
        }

        public VesselPositionMsg(string vessel_name, Geometry.PoseMsg pose, Geographic.GeoPointMsg geo_point)
        {
            this.vessel_name = vessel_name;
            this.pose = pose;
            this.geo_point = geo_point;
        }

        public static VesselPositionMsg Deserialize(MessageDeserializer deserializer) => new VesselPositionMsg(deserializer);

        private VesselPositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vessel_name);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.geo_point = Geographic.GeoPointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vessel_name);
            serializer.Write(this.pose);
            serializer.Write(this.geo_point);
        }

        public override string ToString()
        {
            return "VesselPositionMsg: " +
            "\nvessel_name: " + vessel_name.ToString() +
            "\npose: " + pose.ToString() +
            "\ngeo_point: " + geo_point.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
