//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class WaypointFollowerStatusMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/WaypointFollowerStatus";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string vessel_name;
        //  Name of the vessel
        public byte waypoint_index;
        //  Index of the waypoint reached
        public Geographic.GeoPointMsg[] path;
        //  Path of vessel

        public WaypointFollowerStatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.vessel_name = "";
            this.waypoint_index = 0;
            this.path = new Geographic.GeoPointMsg[0];
        }

        public WaypointFollowerStatusMsg(Std.HeaderMsg header, string vessel_name, byte waypoint_index, Geographic.GeoPointMsg[] path)
        {
            this.header = header;
            this.vessel_name = vessel_name;
            this.waypoint_index = waypoint_index;
            this.path = path;
        }

        public static WaypointFollowerStatusMsg Deserialize(MessageDeserializer deserializer) => new WaypointFollowerStatusMsg(deserializer);

        private WaypointFollowerStatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.vessel_name);
            deserializer.Read(out this.waypoint_index);
            deserializer.Read(out this.path, Geographic.GeoPointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.vessel_name);
            serializer.Write(this.waypoint_index);
            serializer.WriteLength(this.path);
            serializer.Write(this.path);
        }

        public override string ToString()
        {
            return "WaypointFollowerStatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nvessel_name: " + vessel_name.ToString() +
            "\nwaypoint_index: " + waypoint_index.ToString() +
            "\npath: " + System.String.Join(", ", path.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
