// Hand-written to match lotusim_msgs/WindTurbineState ROS2 message definition.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class WindTurbineStateMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/WindTurbineState";
        public override string RosMessageName => k_RosMessageName;

        /// <summary>Turbine identifier — must match the GameObject name in the Unity scene.</summary>
        public string name;

        /// <summary>World position of the turbine (ROS/Gazebo frame, Z-Up).</summary>
        public Geometry.PointMsg position;

        /// <summary>Effective wind speed seen by this turbine after wake effects (m/s).</summary>
        public float effective_wind_speed;

        /// <summary>Power generated by this turbine in Watts.</summary>
        public float power_w;

        public WindTurbineStateMsg()
        {
            this.name = "";
            this.position = new Geometry.PointMsg();
            this.effective_wind_speed = 0f;
            this.power_w = 0f;
        }

        public WindTurbineStateMsg(string name, Geometry.PointMsg position, float effective_wind_speed, float power_w)
        {
            this.name = name;
            this.position = position;
            this.effective_wind_speed = effective_wind_speed;
            this.power_w = power_w;
        }

        public static WindTurbineStateMsg Deserialize(MessageDeserializer deserializer) => new WindTurbineStateMsg(deserializer);

        private WindTurbineStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.effective_wind_speed);
            deserializer.Read(out this.power_w);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.position);
            serializer.Write(this.effective_wind_speed);
            serializer.Write(this.power_w);
        }

        public override string ToString()
        {
            return "WindTurbineStateMsg: " +
            "\nname: " + name +
            "\nposition: " + position.ToString() +
            "\neffective_wind_speed: " + effective_wind_speed.ToString() +
            "\npower_w: " + power_w.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
