//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class WindTurbineStateMsg : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/WindTurbineState";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public Geometry.PointMsg position;
        public float effective_wind_speed;
        public float power_w;

        public WindTurbineStateMsg()
        {
            this.name = "";
            this.position = new Geometry.PointMsg();
            this.effective_wind_speed = 0.0f;
            this.power_w = 0.0f;
        }

        public WindTurbineStateMsg(string name, Geometry.PointMsg position, float effective_wind_speed, float power_w)
        {
            this.name = name;
            this.position = position;
            this.effective_wind_speed = effective_wind_speed;
            this.power_w = power_w;
        }

        public static WindTurbineStateMsg Deserialize(MessageDeserializer deserializer) => new WindTurbineStateMsg(deserializer);

        private WindTurbineStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.effective_wind_speed);
            deserializer.Read(out this.power_w);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.position);
            serializer.Write(this.effective_wind_speed);
            serializer.Write(this.power_w);
        }

        public override string ToString()
        {
            return "WindTurbineStateMsg: " +
            "\nname: " + name.ToString() +
            "\nposition: " + position.ToString() +
            "\neffective_wind_speed: " + effective_wind_speed.ToString() +
            "\npower_w: " + power_w.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
