//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class SetWaypointsResponse : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/SetWaypoints";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public SetWaypointsResponse()
        {
            this.success = false;
        }

        public SetWaypointsResponse(bool success)
        {
            this.success = success;
        }

        public static SetWaypointsResponse Deserialize(MessageDeserializer deserializer) => new SetWaypointsResponse(deserializer);

        private SetWaypointsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SetWaypointsResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
