//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Lotusim
{
    [Serializable]
    public class SetWaypointsRequest : Message
    {
        public const string k_RosMessageName = "lotusim_msgs/SetWaypoints";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geographic.GeoPointMsg[] path;
        public bool loop;

        public SetWaypointsRequest()
        {
            this.header = new Std.HeaderMsg();
            this.path = new Geographic.GeoPointMsg[0];
            this.loop = false;
        }

        public SetWaypointsRequest(Std.HeaderMsg header, Geographic.GeoPointMsg[] path, bool loop)
        {
            this.header = header;
            this.path = path;
            this.loop = loop;
        }

        public static SetWaypointsRequest Deserialize(MessageDeserializer deserializer) => new SetWaypointsRequest(deserializer);

        private SetWaypointsRequest(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.path, Geographic.GeoPointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.loop);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.path);
            serializer.Write(this.path);
            serializer.Write(this.loop);
        }

        public override string ToString()
        {
            return "SetWaypointsRequest: " +
            "\nheader: " + header.ToString() +
            "\npath: " + System.String.Join(", ", path.ToList()) +
            "\nloop: " + loop.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
