//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GeographicMapChangesMsg : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GeographicMapChanges";
        public override string RosMessageName => k_RosMessageName;

        //  A list of geographic map changes.
        public Std.HeaderMsg header;
        //  stamp specifies time of change
        //  frame_id (normally /map)
        public GeographicMapMsg diffs;
        //  new and changed points and features
        public UniqueIdentifier.UUIDMsg[] deletes;
        //  deleted map components

        public GeographicMapChangesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.diffs = new GeographicMapMsg();
            this.deletes = new UniqueIdentifier.UUIDMsg[0];
        }

        public GeographicMapChangesMsg(Std.HeaderMsg header, GeographicMapMsg diffs, UniqueIdentifier.UUIDMsg[] deletes)
        {
            this.header = header;
            this.diffs = diffs;
            this.deletes = deletes;
        }

        public static GeographicMapChangesMsg Deserialize(MessageDeserializer deserializer) => new GeographicMapChangesMsg(deserializer);

        private GeographicMapChangesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.diffs = GeographicMapMsg.Deserialize(deserializer);
            deserializer.Read(out this.deletes, UniqueIdentifier.UUIDMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.diffs);
            serializer.WriteLength(this.deletes);
            serializer.Write(this.deletes);
        }

        public override string ToString()
        {
            return "GeographicMapChangesMsg: " +
            "\nheader: " + header.ToString() +
            "\ndiffs: " + diffs.ToString() +
            "\ndeletes: " + System.String.Join(", ", deletes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
