//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class MapFeatureMsg : Message
    {
        public const string k_RosMessageName = "geographic_msgs/MapFeature";
        public override string RosMessageName => k_RosMessageName;

        //  Geographic map feature.
        // 
        //  A list of WayPoint IDs for features like streets, highways, hiking
        //  trails, the outlines of buildings and parking lots in sequential
        //  order.
        // 
        //  Feature lists may also contain other feature lists as members.
        public UniqueIdentifier.UUIDMsg id;
        //  Unique feature identifier
        public UniqueIdentifier.UUIDMsg[] components;
        //  Sequence of feature components
        public KeyValueMsg[] props;
        //  Key/value properties for this feature

        public MapFeatureMsg()
        {
            this.id = new UniqueIdentifier.UUIDMsg();
            this.components = new UniqueIdentifier.UUIDMsg[0];
            this.props = new KeyValueMsg[0];
        }

        public MapFeatureMsg(UniqueIdentifier.UUIDMsg id, UniqueIdentifier.UUIDMsg[] components, KeyValueMsg[] props)
        {
            this.id = id;
            this.components = components;
            this.props = props;
        }

        public static MapFeatureMsg Deserialize(MessageDeserializer deserializer) => new MapFeatureMsg(deserializer);

        private MapFeatureMsg(MessageDeserializer deserializer)
        {
            this.id = UniqueIdentifier.UUIDMsg.Deserialize(deserializer);
            deserializer.Read(out this.components, UniqueIdentifier.UUIDMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.props, KeyValueMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.WriteLength(this.components);
            serializer.Write(this.components);
            serializer.WriteLength(this.props);
            serializer.Write(this.props);
        }

        public override string ToString()
        {
            return "MapFeatureMsg: " +
            "\nid: " + id.ToString() +
            "\ncomponents: " + System.String.Join(", ", components.ToList()) +
            "\nprops: " + System.String.Join(", ", props.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
