//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UniqueIdentifier
{
    [Serializable]
    public class UUIDMsg : Message
    {
        public const string k_RosMessageName = "unique_identifier_msgs/UUID";
        public override string RosMessageName => k_RosMessageName;

        //  A universally unique identifier (UUID).
        // 
        //   http://en.wikipedia.org/wiki/Universally_unique_identifier
        //   http://tools.ietf.org/html/rfc4122.html
        public byte[] uuid;

        public UUIDMsg()
        {
            this.uuid = new byte[16];
        }

        public UUIDMsg(byte[] uuid)
        {
            this.uuid = uuid;
        }

        public static UUIDMsg Deserialize(MessageDeserializer deserializer) => new UUIDMsg(deserializer);

        private UUIDMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.uuid, sizeof(byte), 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uuid);
        }

        public override string ToString()
        {
            return "UUIDMsg: " +
            "\nuuid: " + System.String.Join(", ", uuid.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
