//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GetGeographicMapRequest : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GetGeographicMap";
        public override string RosMessageName => k_RosMessageName;

        //  This service requests a region of a geographic map.
        public string url;
        //  where to read map data
        //  Bounding box for the desired map.  If all zeros, provide all data
        //  available from the specified URL.
        public BoundingBoxMsg bounds;

        public GetGeographicMapRequest()
        {
            this.url = "";
            this.bounds = new BoundingBoxMsg();
        }

        public GetGeographicMapRequest(string url, BoundingBoxMsg bounds)
        {
            this.url = url;
            this.bounds = bounds;
        }

        public static GetGeographicMapRequest Deserialize(MessageDeserializer deserializer) => new GetGeographicMapRequest(deserializer);

        private GetGeographicMapRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.url);
            this.bounds = BoundingBoxMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.url);
            serializer.Write(this.bounds);
        }

        public override string ToString()
        {
            return "GetGeographicMapRequest: " +
            "\nurl: " + url.ToString() +
            "\nbounds: " + bounds.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
