//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GetGeographicMapResponse : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GetGeographicMap";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  true if the call succeeded
        public string status;
        //  more details
        //  The requested map, its bounds may differ from the requested bounds.
        public GeographicMapMsg map;

        public GetGeographicMapResponse()
        {
            this.success = false;
            this.status = "";
            this.map = new GeographicMapMsg();
        }

        public GetGeographicMapResponse(bool success, string status, GeographicMapMsg map)
        {
            this.success = success;
            this.status = status;
            this.map = map;
        }

        public static GetGeographicMapResponse Deserialize(MessageDeserializer deserializer) => new GetGeographicMapResponse(deserializer);

        private GetGeographicMapResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.status);
            this.map = GeographicMapMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.status);
            serializer.Write(this.map);
        }

        public override string ToString()
        {
            return "GetGeographicMapResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nstatus: " + status.ToString() +
            "\nmap: " + map.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
