//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GetGeoPathResponse : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GetGeoPath";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  true if the call succeeded
        public string status;
        //  more details
        public GeoPathMsg plan;
        //  path to follow
        public UniqueIdentifier.UUIDMsg network;
        //  the uuid of the RouteNetwork
        public UniqueIdentifier.UUIDMsg start_seg;
        //  the uuid of the starting RouteSegment
        public UniqueIdentifier.UUIDMsg goal_seg;
        //  the uuid of the ending RouteSegment
        public double distance;
        //  the length of the plan

        public GetGeoPathResponse()
        {
            this.success = false;
            this.status = "";
            this.plan = new GeoPathMsg();
            this.network = new UniqueIdentifier.UUIDMsg();
            this.start_seg = new UniqueIdentifier.UUIDMsg();
            this.goal_seg = new UniqueIdentifier.UUIDMsg();
            this.distance = 0.0;
        }

        public GetGeoPathResponse(bool success, string status, GeoPathMsg plan, UniqueIdentifier.UUIDMsg network, UniqueIdentifier.UUIDMsg start_seg, UniqueIdentifier.UUIDMsg goal_seg, double distance)
        {
            this.success = success;
            this.status = status;
            this.plan = plan;
            this.network = network;
            this.start_seg = start_seg;
            this.goal_seg = goal_seg;
            this.distance = distance;
        }

        public static GetGeoPathResponse Deserialize(MessageDeserializer deserializer) => new GetGeoPathResponse(deserializer);

        private GetGeoPathResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.status);
            this.plan = GeoPathMsg.Deserialize(deserializer);
            this.network = UniqueIdentifier.UUIDMsg.Deserialize(deserializer);
            this.start_seg = UniqueIdentifier.UUIDMsg.Deserialize(deserializer);
            this.goal_seg = UniqueIdentifier.UUIDMsg.Deserialize(deserializer);
            deserializer.Read(out this.distance);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.status);
            serializer.Write(this.plan);
            serializer.Write(this.network);
            serializer.Write(this.start_seg);
            serializer.Write(this.goal_seg);
            serializer.Write(this.distance);
        }

        public override string ToString()
        {
            return "GetGeoPathResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nstatus: " + status.ToString() +
            "\nplan: " + plan.ToString() +
            "\nnetwork: " + network.ToString() +
            "\nstart_seg: " + start_seg.ToString() +
            "\ngoal_seg: " + goal_seg.ToString() +
            "\ndistance: " + distance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
