//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GetRoutePlanRequest : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GetRoutePlan";
        public override string RosMessageName => k_RosMessageName;

        //  Get a plan to traverse a route network from start to goal.
        // 
        //  Similar to nav_msgs/GetPlan, but constrained to use the route network.
        public UniqueIdentifier.UUIDMsg network;
        //  route network to use
        public UniqueIdentifier.UUIDMsg start;
        //  starting way point
        public UniqueIdentifier.UUIDMsg goal;
        //  goal way point

        public GetRoutePlanRequest()
        {
            this.network = new UniqueIdentifier.UUIDMsg();
            this.start = new UniqueIdentifier.UUIDMsg();
            this.goal = new UniqueIdentifier.UUIDMsg();
        }

        public GetRoutePlanRequest(UniqueIdentifier.UUIDMsg network, UniqueIdentifier.UUIDMsg start, UniqueIdentifier.UUIDMsg goal)
        {
            this.network = network;
            this.start = start;
            this.goal = goal;
        }

        public static GetRoutePlanRequest Deserialize(MessageDeserializer deserializer) => new GetRoutePlanRequest(deserializer);

        private GetRoutePlanRequest(MessageDeserializer deserializer)
        {
            this.network = UniqueIdentifier.UUIDMsg.Deserialize(deserializer);
            this.start = UniqueIdentifier.UUIDMsg.Deserialize(deserializer);
            this.goal = UniqueIdentifier.UUIDMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.network);
            serializer.Write(this.start);
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "GetRoutePlanRequest: " +
            "\nnetwork: " + network.ToString() +
            "\nstart: " + start.ToString() +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
