//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GeoPoseStampedMsg : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GeoPoseStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public GeoPoseMsg pose;

        public GeoPoseStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.pose = new GeoPoseMsg();
        }

        public GeoPoseStampedMsg(Std.HeaderMsg header, GeoPoseMsg pose)
        {
            this.header = header;
            this.pose = pose;
        }

        public static GeoPoseStampedMsg Deserialize(MessageDeserializer deserializer) => new GeoPoseStampedMsg(deserializer);

        private GeoPoseStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.pose = GeoPoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "GeoPoseStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
